/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.uqac.info.runtime;

import ca.uqac.info.monitor.Monitor;
import java.awt.Container;
import java.util.Map;

/**
 *
 * @author Armand
 */
public class MonitorPanel extends javax.swing.JPanel {

    Monitor monitor;

    /**
     * Creates new form MonitorPanel
     */
    public MonitorPanel(Monitor mon, Map<String, String> metadata) {
        initComponents();
        if (mon != null && metadata != null) {
            //Chercher dans les metadatas
            this.monitorLabel.setText(metadata.get("Name"));
            this.monitorFormulaLabel.setText(metadata.get("Formula"));
            this.captionTextField.setText(metadata.get("Caption"));
            this.monitor = mon;
            this.monitorStateLabel.setText(mon.getVerdict().name());

        }
    }

    public MonitorPanel() {
        this(null, null);
    }

    @Override
    public void repaint() {
        super.repaint();
        if (this.monitor != null) {
            this.monitorStateLabel.setText(this.monitor.getVerdict().name());//Actualiser le champ monitorStateLabel
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deleteMonitorButton = new javax.swing.JButton();
        resetMonitorButton = new javax.swing.JButton();
        monitorLabel = new javax.swing.JLabel();
        monitorStateLabel = new javax.swing.JLabel();
        monitorFormulaLabel = new javax.swing.JLabel();
        captionTextField = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        deleteMonitorButton.setText("Delete");
        deleteMonitorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMonitorButtonActionPerformed(evt);
            }
        });

        resetMonitorButton.setText("Reset");
        resetMonitorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetMonitorButtonActionPerformed(evt);
            }
        });

        monitorLabel.setText("monitorLabel");

        monitorStateLabel.setText("monitorStateLabel");

        monitorFormulaLabel.setText("monitorFormulaLabel");

        captionTextField.setText("captionTextField");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(captionTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(monitorLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(monitorStateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(monitorFormulaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resetMonitorButton)
                    .addComponent(deleteMonitorButton))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteMonitorButton)
                    .addComponent(monitorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monitorStateLabel)
                    .addComponent(monitorFormulaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(captionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetMonitorButton))
                .addGap(36, 36, 36))
        );

        deleteMonitorButton.getAccessibleContext().setAccessibleName("deleteMonitorButton");
        resetMonitorButton.getAccessibleContext().setAccessibleName("refreshMonitorButton");
        captionTextField.getAccessibleContext().setAccessibleName("captionTextField");
    }// </editor-fold>//GEN-END:initComponents

    private void deleteMonitorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMonitorButtonActionPerformed
        this.monitor.reset();
        Container parent = this.getParent();
        parent.remove(this);
        parent.repaint(); 
    }//GEN-LAST:event_deleteMonitorButtonActionPerformed

    private void resetMonitorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetMonitorButtonActionPerformed
        this.monitor.reset();
        this.repaint();
    }//GEN-LAST:event_resetMonitorButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField captionTextField;
    private javax.swing.JButton deleteMonitorButton;
    private javax.swing.JLabel monitorFormulaLabel;
    private javax.swing.JLabel monitorLabel;
    private javax.swing.JLabel monitorStateLabel;
    private javax.swing.JButton resetMonitorButton;
    // End of variables declaration//GEN-END:variables
}
